# Generated by Django 5.2.7 on 2025-10-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_options_remove_claim_claim_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed')], default='pending', max_length=20),
        ),
    ]
